# Generated by Django 5.0.9 on 2026-01-22 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryNarration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content_text', models.TextField()),
                ('source_url', models.URLField(blank=True, null=True)),
                ('final_content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storynarration_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storynarration_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
