# Generated by Django 5.0.9 on 2026-01-23 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceritain', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storynarration',
            name='input_token',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storynarration',
            name='output_token',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storynarration',
            name='result_file',
            field=models.FileField(blank=True, null=True, upload_to='story_narration_results/'),
        ),
        migrations.AddField(
            model_name='storynarration',
            name='total_token',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storynarration',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storynarration_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storynarration',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storynarration_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
