# Generated by Django 5.0.9 on 2026-01-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceritain', '0002_storynarration_input_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryNarrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_maintenance', models.BooleanField(default=False, help_text='Enable maintenance mode')),
                ('daily_token_quota', models.IntegerField(default=100000, help_text='Daily token quota limit')),
                ('ai_model', models.CharField(default='gpt-4o-mini-tts', help_text='AI model to use for TTS', max_length=100)),
                ('total_token_used', models.IntegerField(default=0, help_text='Total tokens used')),
                ('voice_type', models.CharField(default='nova', help_text='Voice type for TTS', max_length=50)),
                ('background_music', models.FileField(blank=True, help_text='Background music file', null=True, upload_to='background_music/')),
            ],
            options={
                'verbose_name': 'Story Narration Settings',
                'verbose_name_plural': 'Story Narration Settings',
            },
        ),
    ]
