# Generated by Django 5.0.9 on 2026-01-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceritain', '0003_storynarrationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='storynarration',
            name='message_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storynarrationsettings',
            name='ai_model',
            field=models.CharField(choices=[('tts-1', 'TTS-1'), ('tts-1-hd', 'TTS-1 HD'), ('gpt-4o-mini-tts', 'GPT-4o Mini TTS')], default='gpt-4o-mini-tts', help_text='AI model to use for TTS', max_length=100),
        ),
        migrations.AlterField(
            model_name='storynarrationsettings',
            name='voice_type',
            field=models.CharField(choices=[('alloy', 'Alloy'), ('echo', 'Echo'), ('fable', 'Fable'), ('onyx', 'Onyx'), ('nova', 'Nova'), ('shimmer', 'Shimmer')], default='nova', help_text='Voice type for TTS', max_length=50),
        ),
    ]
