# Generated by Django 5.0.9 on 2026-01-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceritain', '0004_storynarration_message_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storynarration',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
