# Generated by Django 5.0.9 on 2026-01-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceritain', '0005_alter_storynarration_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='storynarrationsettings',
            name='ai_model_txt',
            field=models.CharField(choices=[('gpt-4o-mini', 'GPT-4o Mini'), ('gpt-4.1-nano', 'GPT-4.1 Nano')], default='gpt-4.1-nano', help_text='AI model to use for TTS', max_length=100),
        ),
    ]
