# Generated by Django 5.0.9 on 2026-02-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceritain', '0006_storynarrationsettings_ai_model_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='storynarration',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storynarration',
            name='platform',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storynarrationsettings',
            name='ai_model_txt',
            field=models.CharField(choices=[('gpt-4o-mini', 'GPT-4o Mini'), ('gpt-4.1-nano', 'GPT-4.1 Nano')], default='gpt-4.1-nano', help_text='AI model to use for Generate Text', max_length=100),
        ),
    ]
