# Generated by Django 5.0.9 on 2026-02-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceritain', '0007_storynarration_author_storynarration_platform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storynarration',
            name='content_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storynarration',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storynarration',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
