# Generated by Django 5.0.9 on 2026-02-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceritain', '0008_alter_storynarration_content_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storynarration',
            name='estimated_read_time',
            field=models.IntegerField(default=0),
        ),
    ]
