# Generated by Django 5.0.9 on 2026-02-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceritain', '0009_storynarration_estimated_read_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='storynarration',
            name='play_count',
            field=models.IntegerField(default=0),
        ),
    ]
