# Generated by Django 5.0.9 on 2026-02-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceritain', '0010_storynarration_play_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='storynarration',
            name='background_cover',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
