# Generated by Django 5.0.9 on 2026-02-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceritain', '0011_storynarration_background_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storynarration',
            name='background_cover',
            field=models.TextField(blank=True, null=True),
        ),
    ]
