# Generated by Django 5.0.9 on 2026-08-21 13:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('downloading', 'Downloading'), ('ready', 'Ready to send'), ('rejected', 'Rejected'), ('download_failed', 'Download failed'), ('sent', 'Sent')], default='pending', max_length=20)),
                ('platform', models.CharField(choices=[('tiktok', 'Tiktok')], default='tiktok', max_length=32)),
                ('external_video_id', models.CharField(max_length=255)),
                ('video_url', models.URLField(max_length=500)),
                ('cover_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('author_nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('author_unique_id', models.CharField(blank=True, max_length=255, null=True)),
                ('play_count', models.BigIntegerField(default=0)),
                ('like_count', models.BigIntegerField(default=0)),
                ('comment_count', models.BigIntegerField(default=0)),
                ('share_count', models.BigIntegerField(default=0)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='kontenin/videos/')),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KonteninSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Matikan untuk menghentikan scrape dan pengiriman')),
                ('recipient_group_id', models.CharField(blank=True, help_text='Chat id grup WhatsApp, mis. 12036...@g.us. Pakai `manage.py list_wa_groups` untuk menyalinnya.', max_length=255, null=True)),
                ('recipient_group_name', models.CharField(blank=True, help_text='Nama grup saat id disalin. Pengiriman ditolak kalau nama grup di WhatsApp tidak lagi cocok dengan ini.', max_length=255, null=True)),
                ('verify_group_name', models.BooleanField(default=True, help_text='Cek nama grup sebelum kirim, sebagai pengaman salah tempel id')),
                ('curator_wa_number', models.CharField(blank=True, help_text='Chat id pribadi Curator untuk Low Stock Alert, mis. 62812...@c.us', max_length=255, null=True)),
                ('alert_email', models.EmailField(blank=True, help_text='Tujuan alert kalau openwa mati', max_length=254, null=True)),
                ('low_stock_threshold', models.IntegerField(default=3, help_text='Peringatkan Curator saat Ready Pool turun di bawah angka ini')),
                ('videos_per_delivery', models.IntegerField(default=1)),
                ('max_file_size_mb', models.IntegerField(default=16, help_text='Jaring pengaman terakhir setelah download')),
                ('public_media_base_url', models.URLField(blank=True, help_text='Base URL yang dipakai openwa untuk mengambil mp4, mis. https://palpal.example.com (tanpa trailing slash)', max_length=500, null=True)),
                ('media_cleanup_delay_minutes', models.IntegerField(default=60, help_text='Jeda sebelum mp4 dihapus setelah terkirim. Jangan nol: openwa mungkin masih mengunduh file itu.')),
                ('stale_candidate_days', models.IntegerField(default=30, help_text='Kandidat pending yang tidak di-review selama ini akan dibuang')),
            ],
            options={
                'verbose_name': 'Kontenin Settings',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nama topik, mis. Pertanian', max_length=255)),
                ('keyword', models.CharField(help_text='Kata kunci pencarian TikTok', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_type', models.IntegerField(choices=[(0, 'Relevance'), (1, 'Most liked')], default=0)),
                ('publish_time', models.IntegerField(choices=[(0, 'Any time'), (1, 'Last 24 hours'), (7, 'Last week'), (30, 'Last month'), (90, 'Last 3 months'), (180, 'Last 6 months'), (365, 'Last year')], default=0)),
                ('region', models.CharField(default='ID', max_length=8)),
                ('candidates_per_scrape', models.IntegerField(default=20, help_text='Berapa kandidat diambil per scrape harian')),
                ('max_duration_seconds', models.IntegerField(default=180, help_text='Video lebih panjang dari ini tidak pernah jadi kandidat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('recipient_group_id', models.CharField(max_length=255)),
                ('recipient_group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('media_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('media_cleaned_at', models.DateTimeField(blank=True, null=True)),
                ('wa_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='kontenin.contentcandidate')),
            ],
            options={
                'verbose_name_plural': 'Deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contentcandidate',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='kontenin.topic'),
        ),
        migrations.AddIndex(
            model_name='contentcandidate',
            index=models.Index(fields=['status', 'created_at'], name='kontenin_co_status_9c6f2b_idx'),
        ),
        migrations.AddConstraint(
            model_name='contentcandidate',
            constraint=models.UniqueConstraint(fields=('platform', 'external_video_id'), name='unique_platform_external_video_id'),
        ),
    ]
