# Generated by Django 5.0.9 on 2026-08-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontenin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='konteninsettings',
            name='openwa_session_id',
            field=models.CharField(blank=True, help_text='Session id di OpenWA (bukan nama sesi), mis. 3cd076c5-...', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='konteninsettings',
            name='curator_wa_number',
            field=models.CharField(blank=True, help_text='Chat id pribadi Curator untuk Low Stock Alert, mis. 6281578258854@c.us. Pakai format @c.us - id @lid ditolak oleh route send OpenWA.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='konteninsettings',
            name='media_cleanup_delay_minutes',
            field=models.IntegerField(default=60, help_text='Jeda sebelum mp4 dihapus setelah terkirim. Jangan nol: OpenWA mungkin masih mengunduh file itu.'),
        ),
        migrations.AlterField(
            model_name='konteninsettings',
            name='public_media_base_url',
            field=models.URLField(blank=True, help_text="Base URL publik yang dipakai OpenWA untuk mengambil mp4, mis. https://palpal.codefalah.xyz (tanpa trailing slash). Harus bisa dijangkau dari luar: alamat privat/loopback ditolak OpenWA dengan 'Destination address is not allowed'.", max_length=500, null=True),
        ),
    ]
