# Generated by Django 5.0.9 on 2026-08-22 00:35

from django.db import migrations, models

OLD_DEFAULT = 180


def lift_old_default(apps, schema_editor):
    """
    Existing Topics still sitting on the old 180s default get the limit lifted.

    Only rows at exactly the old default are touched - a Topic where someone
    deliberately typed a different limit keeps it.
    """
    Topic = apps.get_model('kontenin', 'Topic')
    Topic.objects.filter(max_duration_seconds=OLD_DEFAULT).update(max_duration_seconds=0)


def restore_old_default(apps, schema_editor):
    Topic = apps.get_model('kontenin', 'Topic')
    Topic.objects.filter(max_duration_seconds=0).update(max_duration_seconds=OLD_DEFAULT)


class Migration(migrations.Migration):

    dependencies = [
        ('kontenin', '0002_konteninsettings_openwa_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='max_duration_seconds',
            field=models.IntegerField(default=0, help_text='Batas durasi kandidat, dalam detik. 0 = tanpa batas. Durasi bukan lagi penyaring utama - yang mengikat adalah max_file_size_mb, dan itu baru ketahuan setelah download.'),
        ),
        migrations.RunPython(lift_old_default, restore_old_default),
    ]
