volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_django_media: {}
  production_redis_data: {}



services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: palpal_production_django
    volumes:
      - production_django_media:/app/palpal/media
      - /var/www/palpal/media:/app/palpal/media
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    ports:
      - '127.0.0.1:8000:5000'

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: palpal_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: docker.io/redis:6
    volumes:
      - production_redis_data:/data


  celeryworker:
    <<: *django
    image: palpal_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: palpal_production_celerybeat
    command: /start-celerybeat
    ports:
      - '127.0.0.1:8001:5000'

  flower:
    <<: *django
    image: palpal_production_flower
    command: /start-flower
    ports:
      - '127.0.0.1:5555:5555'
