# Generated by Django 5.0.9 on 2025-06-02 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yttoolkit', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YoutubeMp3Downloader',
            new_name='YouTubeMP3',
        ),
    ]
