# Generated by Django 5.0.9 on 2025-06-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yttoolkit', '0002_rename_youtubemp3downloader_youtubemp3'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubemp3',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youtubemp3',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='youtubemp3',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='youtubemp3',
            name='video_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
