# Generated by Django 5.0.9 on 2025-06-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yttoolkit', '0003_youtubemp3_error_message_youtubemp3_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubemp3',
            name='file_path',
            field=models.CharField(blank=True, help_text='Path to the downloaded MP3 file', max_length=500, null=True),
        ),
    ]
