# Generated by Django 5.0.9 on 2025-12-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokorean', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manhwa',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='zip_files/'),
        ),
        migrations.AlterField(
            model_name='manhwa',
            name='download_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('in progress', 'In Progress')], default='pending', max_length=255),
        ),
    ]
