# Generated by Django 5.0.9 on 2024-11-20 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_name', models.CharField(max_length=100, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cookie_data', models.JSONField(default=dict, verbose_name='Cookie Data')),
            ],
            options={
                'verbose_name': 'Cookie',
                'verbose_name_plural': 'Cookies',
                'ordering': ['cookie_data'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag_name', models.CharField(max_length=100, verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['tag_name'],
            },
        ),
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_name', models.CharField(max_length=255, verbose_name='Group Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon', models.ImageField(upload_to=None, verbose_name='Icon')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='master.category', verbose_name='Category')),
                ('cookie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cookie', to='master.cookie', verbose_name='Cookie')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tag', to='master.tag', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Item Group',
                'verbose_name_plural': 'Item Groups',
                'ordering': ['group_name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_name', models.CharField(max_length=255, verbose_name='Item Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('json_property', models.JSONField(default=dict, verbose_name='JSON Property')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='master.itemgroup', verbose_name='Item Group')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['item_name'],
                'indexes': [models.Index(fields=['group', 'item_name'], name='master_item_group_i_bda6c4_idx')],
            },
        ),
    ]
