# Generated by Django 5.0.9 on 2024-11-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemgroup',
            name='tag',
        ),
        migrations.AddField(
            model_name='itemgroup',
            name='tags',
            field=models.ManyToManyField(related_name='item_groups', to='master.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='itemgroup',
            name='icon',
            field=models.ImageField(upload_to='item-group', verbose_name='Icon'),
        ),
    ]
