# Generated by Django 5.0.9 on 2025-04-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_remove_itemgroup_tag_itemgroup_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemgroup',
            name='cookie',
        ),
        migrations.AddField(
            model_name='itemgroup',
            name='cookie_data',
            field=models.JSONField(default=dict, verbose_name='Cookie Data'),
        ),
        migrations.AlterField(
            model_name='itemgroup',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
    ]
