# Generated by Django 5.0.9 on 2025-04-16 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_remove_itemgroup_cookie_itemgroup_cookie_data_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cookie',
        ),
    ]
