# Generated by Django 5.0.9 on 2025-04-16 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_delete_cookie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemgroup',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
