# Generated by Django 5.0.9 on 2025-06-20 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_remove_itemgroup_category_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Cookie Name')),
                ('application', models.CharField(choices=[('youtube', 'YouTube'), ('instagram', 'Instagram'), ('shopee', 'Shopee'), ('tiktok', 'TikTok'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('other', 'Other')], default='other', max_length=50, verbose_name='Application')),
                ('cookie_data', models.JSONField(help_text='JSON format cookie data from the application', verbose_name='Cookie Data')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('domain', models.CharField(blank=True, max_length=255, null=True, verbose_name='Domain')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
            ],
            options={
                'verbose_name': 'Cookie',
                'verbose_name_plural': 'Cookies',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['application', 'is_active'], name='master_cook_applica_defd96_idx'), models.Index(fields=['domain', 'is_active'], name='master_cook_domain_e52c70_idx')],
            },
        ),
    ]
