# Generated by Django 5.0.9 on 2025-06-20 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_cookie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookie',
            name='expires_at',
        ),
    ]
