#!/usr/bin/env python3
"""
Django management command to refresh YouTube cookies using Celery task.

Usage:
    python manage.py refresh_cookies
    python manage.py refresh_cookies --cookie-file /path/to/cookies.txt
    python manage.py refresh_cookies --chromium
    python manage.py refresh_cookies --sync  # Run synchronously without Celery
"""

import os
from django.core.management.base import BaseCommand, CommandError
from django.conf import settings


class Command(BaseCommand):
    help = 'Refresh YouTube cookies for authentication'

    def add_arguments(self, parser):
        parser.add_argument(
            '--cookie-file',
            type=str,
            help='Path to the cookies.txt file (default: from settings or /tmp/cookies.txt)',
        )
        parser.add_argument(
            '--chromium',
            action='store_true',
            help='Use Chromium browser instead of Chrome',
        )
        parser.add_argument(
            '--sync',
            action='store_true',
            help='Run synchronously without Celery (for testing)',
        )
        parser.add_argument(
            '--test-only',
            action='store_true',
            help='Only test existing cookies without refreshing',
        )

    def handle(self, *args, **options):
        cookie_file = options.get('cookie_file')
        use_chromium = options.get('chromium', False)
        sync_mode = options.get('sync', False)
        test_only = options.get('test_only', False)

        # Determine cookie file path
        if not cookie_file:
            cookie_file = getattr(settings, 'YOUTUBE_COOKIES_PATH', '/tmp/cookies.txt')

        self.stdout.write(f"Using cookie file: {cookie_file}")
        if use_chromium:
            self.stdout.write("Using Chromium browser")

        if test_only:
            self.test_cookies_only(cookie_file)
            return

        if sync_mode:
            self.run_sync(cookie_file, use_chromium)
        else:
            self.run_async(cookie_file, use_chromium)

    def test_cookies_only(self, cookie_file):
        """Test existing cookies without refreshing"""
        try:
            from yttoolkit.refresh_cookie import test_cookies, test_authenticated_access

            if not os.path.exists(cookie_file):
                raise CommandError(f"Cookie file {cookie_file} not found!")

            self.stdout.write("Testing existing cookies...")

            # Test basic functionality
            test_result = test_cookies(cookie_file)
            if test_result:
                self.stdout.write(
                    self.style.SUCCESS("✅ Basic cookie test passed")
                )
            else:
                self.stdout.write(
                    self.style.ERROR("❌ Basic cookie test failed")
                )

            # Test authenticated access
            auth_result = test_authenticated_access(cookie_file)
            if auth_result:
                self.stdout.write(
                    self.style.SUCCESS("✅ Authenticated access test passed")
                )
            else:
                self.stdout.write(
                    self.style.ERROR("❌ Authenticated access test failed")
                )

            if test_result and auth_result:
                self.stdout.write(
                    self.style.SUCCESS("🎉 All cookie tests passed!")
                )
            else:
                self.stdout.write(
                    self.style.WARNING("⚠️  Some cookie tests failed. Consider refreshing cookies.")
                )

        except ImportError as e:
            raise CommandError(f"Could not import refresh_cookie module: {e}")
        except Exception as e:
            raise CommandError(f"Error testing cookies: {e}")

    def run_sync(self, cookie_file, use_chromium):
        """Run cookie refresh synchronously"""
        try:
            from yttoolkit.refresh_cookie import (
                update_cookies,
                test_cookies,
                test_authenticated_access,
                clean_expired_cookies
            )

            self.stdout.write("Running cookie refresh synchronously...")

            # Check if cookie file exists
            if not os.path.exists(cookie_file):
                # Create empty cookie file if it doesn't exist
                os.makedirs(os.path.dirname(cookie_file), exist_ok=True)
                with open(cookie_file, 'w') as f:
                    f.write("# Netscape HTTP Cookie File\n")
                    f.write("# Generated by refresh_cookies command\n\n")
                self.stdout.write(f"Created new cookie file: {cookie_file}")

            # Clean expired cookies first
            self.stdout.write("Cleaning expired cookies...")
            clean_expired_cookies(cookie_file)

            # Refresh cookies
            self.stdout.write("Refreshing cookies...")
            refresh_result = update_cookies(cookie_file, use_chromium)

            if not refresh_result:
                raise CommandError("Cookie refresh failed!")

            # Test the refreshed cookies
            self.stdout.write("Testing refreshed cookies...")
            test_result = test_cookies(cookie_file)
            auth_result = test_authenticated_access(cookie_file)

            # Final cleanup
            clean_expired_cookies(cookie_file)

            # Report results
            if refresh_result:
                self.stdout.write(
                    self.style.SUCCESS("✅ Cookies refreshed successfully!")
                )

            if test_result:
                self.stdout.write(
                    self.style.SUCCESS("✅ Cookie test passed")
                )
            else:
                self.stdout.write(
                    self.style.WARNING("⚠️  Cookie test failed")
                )

            if auth_result:
                self.stdout.write(
                    self.style.SUCCESS("✅ Authenticated access test passed")
                )
            else:
                self.stdout.write(
                    self.style.WARNING("⚠️  Authenticated access test failed")
                )

            if refresh_result and test_result and auth_result:
                self.stdout.write(
                    self.style.SUCCESS("🎉 Cookie refresh completed successfully!")
                )
            else:
                self.stdout.write(
                    self.style.WARNING("⚠️  Cookie refresh completed with some issues")
                )

        except ImportError as e:
            raise CommandError(f"Could not import refresh_cookie module: {e}")
        except Exception as e:
            raise CommandError(f"Error during cookie refresh: {e}")

    def run_async(self, cookie_file, use_chromium):
        """Run cookie refresh using Celery task"""
        try:
            from yttoolkit.tasks import refresh_youtube_cookies

            self.stdout.write("Scheduling cookie refresh task...")

            # Start the Celery task
            result = refresh_youtube_cookies.delay(cookie_file, use_chromium)

            self.stdout.write(f"Task scheduled with ID: {result.id}")
            self.stdout.write("Waiting for task to complete...")

            # Wait for the task to complete and get the result
            task_result = result.get(timeout=300)  # 5 minute timeout

            if task_result['status'] == 'success':
                self.stdout.write(
                    self.style.SUCCESS(f"✅ {task_result['message']}")
                )
                self.stdout.write(f"Cookie file: {task_result['cookie_file']}")
                self.stdout.write(f"Browser used: {task_result['browser_used']}")

                if task_result.get('test_passed'):
                    self.stdout.write(
                        self.style.SUCCESS("✅ Cookie test passed")
                    )
                else:
                    self.stdout.write(
                        self.style.WARNING("⚠️  Cookie test failed")
                    )

                if task_result.get('auth_test_passed'):
                    self.stdout.write(
                        self.style.SUCCESS("✅ Authenticated access test passed")
                    )
                else:
                    self.stdout.write(
                        self.style.WARNING("⚠️  Authenticated access test failed")
                    )
            else:
                self.stdout.write(
                    self.style.ERROR(f"❌ {task_result['message']}")
                )

        except ImportError as e:
            raise CommandError(f"Could not import Celery task: {e}")
        except Exception as e:
            raise CommandError(f"Error running async task: {e}")
