# Generated by Django 5.0.9 on 2026-03-10 23:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, choices=[('tiktok', 'Tiktok'), ('instagram', 'Instagram'), ('youtube', 'Youtube'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('other', 'Other')], max_length=255, null=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('external_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('external_unique_id', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar_url_list', models.JSONField(blank=True, null=True)),
                ('avatar_url_prefix', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
