# Generated by Django 5.0.9 on 2026-03-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialcomment',
            name='video_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialcomment',
            name='platform',
            field=models.CharField(blank=True, choices=[('tiktok', 'Tiktok'), ('instagram', 'Instagram'), ('youtube', 'Youtube'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('other', 'Other')], default='tiktok', max_length=255, null=True),
        ),
    ]
