log:
  level: INFO

entryPoints:
  web:
    # http
    address: ':80'
    # Removed HTTPS redirect for IP-based access

  web-secure:
    # https (can be used for HTTP when no TLS)
    address: ':443'

  flower:
    address: ':5555'

# certificatesResolvers:
#   letsencrypt:
#     # https://doc.traefik.io/traefik/https/acme/#lets-encrypt
#     acme:
#       email: 'zulfafalah@gmail.com'
#       storage: /etc/traefik/acme/acme.json
#       # https://doc.traefik.io/traefik/https/acme/#httpchallenge
#       httpChallenge:
#         entryPoint: web

http:
  routers:
    web-router:
      rule: 'Host(`159.223.48.89`)'
      entryPoints:
        - web
      middlewares:
        - csrf
      service: django

    web-secure-router:
      rule: 'Host(`159.223.48.89`)'
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django
      # Removed TLS for IP-based access

    flower-secure-router:
      rule: 'Host(`159.223.48.89`)'
      entryPoints:
        - flower
      service: flower
      # Removed TLS for IP-based access

    web-media-router:
      rule: 'Host(`159.223.48.89`) && PathPrefix(`/media/`)'
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django-media
      # Removed TLS for IP-based access

  middlewares:
    csrf:
      # https://doc.traefik.io/traefik/master/middlewares/http/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: ['X-CSRFToken']

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5000

    flower:
      loadBalancer:
        servers:
          - url: http://flower:5555

    django-media:
      loadBalancer:
        servers:
          - url: http://nginx:80

providers:
  # https://doc.traefik.io/traefik/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
