# Generated by Django 5.0.9 on 2025-03-26 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0002_remove_itemgroup_tag_itemgroup_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.CharField(max_length=50, verbose_name='Order ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('status_order', models.CharField(choices=[('not_started', 'Not Started'), ('complete', 'Complete'), ('pending', 'Pending'), ('refund', 'Refund')], default='not_started', max_length=20, verbose_name='Status')),
                ('is_refund', models.BooleanField(verbose_name='Is Refund')),
                ('file_data', models.CharField(max_length=255, verbose_name='File Data')),
                ('service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.item', verbose_name='Service Name')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
