# Generated by Django 5.0.9 on 2025-04-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='file_data',
            field=models.CharField(max_length=255, null=True, verbose_name='File Data'),
        ),
    ]
