# Generated by Django 5.0.9 on 2025-04-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_salesorder_file_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='file_data',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='File Data'),
        ),
    ]
