# Generated by Django 5.0.9 on 2025-04-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_salesorder_file_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='is_refund',
            field=models.BooleanField(default=False, verbose_name='Is Refund'),
        ),
    ]
